development:
  adapter: postgresql
  encoding: unicode
  database: kando_development
  pool: 5
  timeout: 5000
  username: nadavk72
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5
  timeout: 5000
  username: nadavk72
  password: 
