require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CorporatesController do

  # This should return the minimal set of attributes required to create a valid
  # Corporate. As you add validations to Corporate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CorporatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all corporates as @corporates" do
      corporate = Corporate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:corporates).should eq([corporate])
    end
  end

  describe "GET show" do
    it "assigns the requested corporate as @corporate" do
      corporate = Corporate.create! valid_attributes
      get :show, {:id => corporate.to_param}, valid_session
      assigns(:corporate).should eq(corporate)
    end
  end

  describe "GET new" do
    it "assigns a new corporate as @corporate" do
      get :new, {}, valid_session
      assigns(:corporate).should be_a_new(Corporate)
    end
  end

  describe "GET edit" do
    it "assigns the requested corporate as @corporate" do
      corporate = Corporate.create! valid_attributes
      get :edit, {:id => corporate.to_param}, valid_session
      assigns(:corporate).should eq(corporate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Corporate" do
        expect {
          post :create, {:corporate => valid_attributes}, valid_session
        }.to change(Corporate, :count).by(1)
      end

      it "assigns a newly created corporate as @corporate" do
        post :create, {:corporate => valid_attributes}, valid_session
        assigns(:corporate).should be_a(Corporate)
        assigns(:corporate).should be_persisted
      end

      it "redirects to the created corporate" do
        post :create, {:corporate => valid_attributes}, valid_session
        response.should redirect_to(Corporate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved corporate as @corporate" do
        # Trigger the behavior that occurs when invalid params are submitted
        Corporate.any_instance.stub(:save).and_return(false)
        post :create, {:corporate => { "name" => "invalid value" }}, valid_session
        assigns(:corporate).should be_a_new(Corporate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Corporate.any_instance.stub(:save).and_return(false)
        post :create, {:corporate => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested corporate" do
        corporate = Corporate.create! valid_attributes
        # Assuming there are no other corporates in the database, this
        # specifies that the Corporate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Corporate.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => corporate.to_param, :corporate => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested corporate as @corporate" do
        corporate = Corporate.create! valid_attributes
        put :update, {:id => corporate.to_param, :corporate => valid_attributes}, valid_session
        assigns(:corporate).should eq(corporate)
      end

      it "redirects to the corporate" do
        corporate = Corporate.create! valid_attributes
        put :update, {:id => corporate.to_param, :corporate => valid_attributes}, valid_session
        response.should redirect_to(corporate)
      end
    end

    describe "with invalid params" do
      it "assigns the corporate as @corporate" do
        corporate = Corporate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Corporate.any_instance.stub(:save).and_return(false)
        put :update, {:id => corporate.to_param, :corporate => { "name" => "invalid value" }}, valid_session
        assigns(:corporate).should eq(corporate)
      end

      it "re-renders the 'edit' template" do
        corporate = Corporate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Corporate.any_instance.stub(:save).and_return(false)
        put :update, {:id => corporate.to_param, :corporate => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested corporate" do
      corporate = Corporate.create! valid_attributes
      expect {
        delete :destroy, {:id => corporate.to_param}, valid_session
      }.to change(Corporate, :count).by(-1)
    end

    it "redirects to the corporates list" do
      corporate = Corporate.create! valid_attributes
      delete :destroy, {:id => corporate.to_param}, valid_session
      response.should redirect_to(corporates_url)
    end
  end

end
