require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FactoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Factory. As you add validations to Factory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FactoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all factories as @factories" do
      factory = Factory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:factories).should eq([factory])
    end
  end

  describe "GET show" do
    it "assigns the requested factory as @factory" do
      factory = Factory.create! valid_attributes
      get :show, {:id => factory.to_param}, valid_session
      assigns(:factory).should eq(factory)
    end
  end

  describe "GET new" do
    it "assigns a new factory as @factory" do
      get :new, {}, valid_session
      assigns(:factory).should be_a_new(Factory)
    end
  end

  describe "GET edit" do
    it "assigns the requested factory as @factory" do
      factory = Factory.create! valid_attributes
      get :edit, {:id => factory.to_param}, valid_session
      assigns(:factory).should eq(factory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Factory" do
        expect {
          post :create, {:factory => valid_attributes}, valid_session
        }.to change(Factory, :count).by(1)
      end

      it "assigns a newly created factory as @factory" do
        post :create, {:factory => valid_attributes}, valid_session
        assigns(:factory).should be_a(Factory)
        assigns(:factory).should be_persisted
      end

      it "redirects to the created factory" do
        post :create, {:factory => valid_attributes}, valid_session
        response.should redirect_to(Factory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved factory as @factory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Factory.any_instance.stub(:save).and_return(false)
        post :create, {:factory => { "name" => "invalid value" }}, valid_session
        assigns(:factory).should be_a_new(Factory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Factory.any_instance.stub(:save).and_return(false)
        post :create, {:factory => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested factory" do
        factory = Factory.create! valid_attributes
        # Assuming there are no other factories in the database, this
        # specifies that the Factory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Factory.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => factory.to_param, :factory => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested factory as @factory" do
        factory = Factory.create! valid_attributes
        put :update, {:id => factory.to_param, :factory => valid_attributes}, valid_session
        assigns(:factory).should eq(factory)
      end

      it "redirects to the factory" do
        factory = Factory.create! valid_attributes
        put :update, {:id => factory.to_param, :factory => valid_attributes}, valid_session
        response.should redirect_to(factory)
      end
    end

    describe "with invalid params" do
      it "assigns the factory as @factory" do
        factory = Factory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Factory.any_instance.stub(:save).and_return(false)
        put :update, {:id => factory.to_param, :factory => { "name" => "invalid value" }}, valid_session
        assigns(:factory).should eq(factory)
      end

      it "re-renders the 'edit' template" do
        factory = Factory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Factory.any_instance.stub(:save).and_return(false)
        put :update, {:id => factory.to_param, :factory => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested factory" do
      factory = Factory.create! valid_attributes
      expect {
        delete :destroy, {:id => factory.to_param}, valid_session
      }.to change(Factory, :count).by(-1)
    end

    it "redirects to the factories list" do
      factory = Factory.create! valid_attributes
      delete :destroy, {:id => factory.to_param}, valid_session
      response.should redirect_to(factories_url)
    end
  end

end
