require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SewageFarmsController do

  # This should return the minimal set of attributes required to create a valid
  # SewageFarm. As you add validations to SewageFarm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SewageFarmsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sewage_farms as @sewage_farms" do
      sewage_farm = SewageFarm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sewage_farms).should eq([sewage_farm])
    end
  end

  describe "GET show" do
    it "assigns the requested sewage_farm as @sewage_farm" do
      sewage_farm = SewageFarm.create! valid_attributes
      get :show, {:id => sewage_farm.to_param}, valid_session
      assigns(:sewage_farm).should eq(sewage_farm)
    end
  end

  describe "GET new" do
    it "assigns a new sewage_farm as @sewage_farm" do
      get :new, {}, valid_session
      assigns(:sewage_farm).should be_a_new(SewageFarm)
    end
  end

  describe "GET edit" do
    it "assigns the requested sewage_farm as @sewage_farm" do
      sewage_farm = SewageFarm.create! valid_attributes
      get :edit, {:id => sewage_farm.to_param}, valid_session
      assigns(:sewage_farm).should eq(sewage_farm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SewageFarm" do
        expect {
          post :create, {:sewage_farm => valid_attributes}, valid_session
        }.to change(SewageFarm, :count).by(1)
      end

      it "assigns a newly created sewage_farm as @sewage_farm" do
        post :create, {:sewage_farm => valid_attributes}, valid_session
        assigns(:sewage_farm).should be_a(SewageFarm)
        assigns(:sewage_farm).should be_persisted
      end

      it "redirects to the created sewage_farm" do
        post :create, {:sewage_farm => valid_attributes}, valid_session
        response.should redirect_to(SewageFarm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sewage_farm as @sewage_farm" do
        # Trigger the behavior that occurs when invalid params are submitted
        SewageFarm.any_instance.stub(:save).and_return(false)
        post :create, {:sewage_farm => { "name" => "invalid value" }}, valid_session
        assigns(:sewage_farm).should be_a_new(SewageFarm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SewageFarm.any_instance.stub(:save).and_return(false)
        post :create, {:sewage_farm => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sewage_farm" do
        sewage_farm = SewageFarm.create! valid_attributes
        # Assuming there are no other sewage_farms in the database, this
        # specifies that the SewageFarm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SewageFarm.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => sewage_farm.to_param, :sewage_farm => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested sewage_farm as @sewage_farm" do
        sewage_farm = SewageFarm.create! valid_attributes
        put :update, {:id => sewage_farm.to_param, :sewage_farm => valid_attributes}, valid_session
        assigns(:sewage_farm).should eq(sewage_farm)
      end

      it "redirects to the sewage_farm" do
        sewage_farm = SewageFarm.create! valid_attributes
        put :update, {:id => sewage_farm.to_param, :sewage_farm => valid_attributes}, valid_session
        response.should redirect_to(sewage_farm)
      end
    end

    describe "with invalid params" do
      it "assigns the sewage_farm as @sewage_farm" do
        sewage_farm = SewageFarm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SewageFarm.any_instance.stub(:save).and_return(false)
        put :update, {:id => sewage_farm.to_param, :sewage_farm => { "name" => "invalid value" }}, valid_session
        assigns(:sewage_farm).should eq(sewage_farm)
      end

      it "re-renders the 'edit' template" do
        sewage_farm = SewageFarm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SewageFarm.any_instance.stub(:save).and_return(false)
        put :update, {:id => sewage_farm.to_param, :sewage_farm => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sewage_farm" do
      sewage_farm = SewageFarm.create! valid_attributes
      expect {
        delete :destroy, {:id => sewage_farm.to_param}, valid_session
      }.to change(SewageFarm, :count).by(-1)
    end

    it "redirects to the sewage_farms list" do
      sewage_farm = SewageFarm.create! valid_attributes
      delete :destroy, {:id => sewage_farm.to_param}, valid_session
      response.should redirect_to(sewage_farms_url)
    end
  end

end
